// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-03-27 09:38:46.51672 +0800 CST m=+0.050584441

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "服务，以下为所有api接口。",
        "title": "服务",
        "contact": {},
        "license": {},
        "version": "1.0"
    },
    "host": "www.baidu.com",
    "basePath": "/v1",
    "paths": {
        "/api/v1/get-test": {
            "get": {
                "description": "Get请求测试",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test"
                ],
                "summary": "Get请求测试",
                "parameters": [
                    {
                        "description": "page required",
                        "name": "page",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    },
                    {
                        "description": "pageSize required",
                        "name": "pageSize",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"page\":1,\"pageSize\":20},\"msg\":\"success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":\"Key: 'Params.PageSize' Error:Field validation for 'PageSize' failed on the 'required' tag\",\"msg\":\"params error\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "{\"code\":405,\"data\":null,\"msg\":\"每页不能超过50个\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/post-test": {
            "post": {
                "description": "POST请求测试",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test"
                ],
                "summary": "POST请求测试",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"page\":1,\"pageSize\":20},\"msg\":\"success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"data\":\"Key: 'Params.PageSize' Error:Field validation for 'PageSize' failed on the 'required' tag\",\"msg\":\"params error\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "{\"code\":405,\"data\":null,\"msg\":\"每页不能超过50个\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
